// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAor36JClRx7O0NhMSw0u9dXZJiWVEVnRU',
    appId: '1:164063284685:web:00f07ea56970f265068884',
    messagingSenderId: '164063284685',
    projectId: 'jcp-jordan',
    authDomain: 'jcp-jordan.firebaseapp.com',
    storageBucket: 'jcp-jordan.firebasestorage.app',
    measurementId: 'G-X8KEX4FE0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlioIW8k9G5D_wjubF6EvUK_m3FAuRbiY',
    appId: '1:164063284685:android:b98a1f9cf50ca4fd068884',
    messagingSenderId: '164063284685',
    projectId: 'jcp-jordan',
    storageBucket: 'jcp-jordan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSVSFOfTASe69xrrVBM9zS0pdQbiTdq9s',
    appId: '1:164063284685:ios:d4781037c339061a068884',
    messagingSenderId: '164063284685',
    projectId: 'jcp-jordan',
    storageBucket: 'jcp-jordan.firebasestorage.app',
    iosBundleId: 'scp.hajras.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSVSFOfTASe69xrrVBM9zS0pdQbiTdq9s',
    appId: '1:164063284685:ios:4b159d629581ea9e068884',
    messagingSenderId: '164063284685',
    projectId: 'jcp-jordan',
    storageBucket: 'jcp-jordan.firebasestorage.app',
    iosBundleId: 'com.example.jcpVs1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAor36JClRx7O0NhMSw0u9dXZJiWVEVnRU',
    appId: '1:164063284685:web:e87d5f089350601a068884',
    messagingSenderId: '164063284685',
    projectId: 'jcp-jordan',
    authDomain: 'jcp-jordan.firebaseapp.com',
    storageBucket: 'jcp-jordan.firebasestorage.app',
    measurementId: 'G-77M0NVQ5PC',
  );

}